language: node_js
dist: jammy
node_js:
- 22.5.1
script:
- echo "hello world"
- npm install
- make
- npm run web
- cd ide
- npm install
deploy:
  api_key:
    secure: i7eMzzsJCpLNQjBRomrWTn27LZYtq6KtryxF1JsqeHNxTehJrNMmRiUZOPWb9a5CCvDnH/+nlGbN4UdYMhRc8n9p4oN/K3THShbHh9g7MGJC4AQl94H4RNZVlAJTT9oGKapg4AelbM6P1HLnA24hNHs3fwGWt5KXOJGwm0U0pyBDM8Zlyg0iACinadug16zccIUZmDl4WwHEL9tcR7YYcz4/NSJQiGmVnDivyM7s1OevzN2M4naWPP1f5mRSmMLPvMYISxMb6Y1KmBHvXXeVHWhczCgNyG1AEwzPcieOm8KCO0jjPDg/9Ig58HHurcgoKOLH/RubpxxwKeSRhTiUiJ1Un/uALYmWkQWuMjmiIc4OA1PUKqR9R1rosUMRxmmSTJxg2uPPqE7kEAwUB8qBdflrlZd/39zOfiMx2LCVecgzhTjMONd9xUm/RjgbHeJPnxLz5eB3ourQ5vKtti2cXr9M6eNo9O/eJ8kRngPlNRgDSLu+iW95HezPuh9Anu6U8j8CeRk23CDYYHVB0l89VI91Ax/kCKmlcbxDc9zXMj5gBvgwwGa/EIaB8iuVQYDQsP7aI9bGJuif3kj6Jaqv23tKnJD6UlZz1NC0IfEPoirSe3Rwfgc0kT+/7olXWwgGHWGuqXrEUt/3QB3Ad79Mgk9f7PDWC+m3/VTmOxu8Al0=
