language: node_js
dist: jammy
node_js:
- 22.5.1
cache:
  directories:
    - .pyret/compiled
    - build/phaseA
    - build/runtime
    - build/worker
    - node_modules
    - src/arr/compiler/ts-*.js
    - src/runtime-arr/compiled
    - src/runtime-arr-preludes/compiled
    - ide/node_modules
script:
- echo "hello world"
- npm install
- make
- npm run web
- cd ide && npm install && npm run build && cd ..
deploy:
  provider: heroku
  app: th-pyret-lang
  api_key:
    secure: "LFgJ/jpyFLSSxTerQbRFx7o0PRa5scaOZWYWhTtnYAdtKsy8cFko2lJMsolEGxcjYMG2cr4BJT1OFkyMWJCwrXj2i6c8TxqcqtJ0D9KNMx7xikxm9AifFFLPqQQH8PUllrJIIQZjpAAG/1PiEl/KnzeDjmobbkwnUu3ITGDnFjvLSnTOYEWhLDisz1jX+XvojuuWUJAThZzJTHj1MAATuzEMqShmrk9HG4VYX81mwbwctReppwJouzcmhsONfXrg1aSq2u5fOjgieTsaIQjY+lfuknRN75A/anVJwZw1twHscdnYSVE0/eu7Pf7KzPgNnkyoEzRr4lRSwW0DawL0fjBv7AShOKqkItONu3R0TqntcVO/Q+U3AxB6JBhnRbxRjH/7Ylf4wNn8nmgZWiKjyKPqZup8aLYwgoKbIU9sqU16OArndjOvsBVsbExiHzVTsVDlYUz3WIU8cYPsZ71eRYojtuhDsBPMJNOsj3VIxorYmYcX39AimE7BFyOU5hCryD4cdivhXBQxGWsusIbwRQmaxTEUtunVVMddtDZL8TE2LeHDrBOJlQaiTe61UU0CFeFTNQL9DoG+fjA+p6NSiGPMUb4VG0uZQJ9l5Ztf8/8PMoR0kXtvDtDtJKegbNvzdKHGA1cKOKugLG9sq729ejCMp01S72hQ0p8CZbzBzUE="
  on:
    all-branches: true
  environment:
    NODE_ENV: production
  skip_cleanup: true
