language: node_js
dist: jammy
node_js:
- 22.5.1
cache:
  directories:
  - ide/node_modules
script:
- echo "hello world"
- npm install
- make
- npm run web
- cd ide && npm install && npm run build && cd ..
before_deploy:
  - echo ".pyret/compiled" >> .gitignore
  - echo build/phaseA >> .gitignore
  - echo build/runtime >> .gitignore
  - echo build/worker >> .gitignore
  - echo node_modules >> .gitignore
  - echo "src/arr/compiler/ts-*.js" >> .gitignore
  - echo src/runtime-arr/compiled >> .gitignore
  - echo src/runtime-arr-preludes/compiled >> .gitignore
deploy:
  provider: heroku
  app: th-pyret-lang
  api_key:
    secure: WqCqm+fRwOq+pMDZm0aEJF3Q857ltj1A4fAjW0mhEmXIYxPVUpfqvCQDN+buvEGLloQ0JjrHs2YShb/DgvI1sGZ1IXd2Psudi8BIIUJVv441brklT/eDSIwa/rIrez4YyLWkrYoyunbnQN+QMLbLghLsemVy9eEKNHHIBTyGMA3jG7L0Nj8VLfIG24WAfnawI6oAAbfBSFuHWuRIbNhxQ087gkqhI0TtiCuK3AP5vBT/wxd+rfHOyXuq1uAt5hTFiVCChaOV6AnS08NOqXs0jy6xKDgZ/VDYjFgTiSaKdmrrrB4aNs13RCS7E8fUsXgLezytrVNDbXRr5NcOfRMUhwcH8kYBJ4meIugUsPX+HWOP8iPEua5U+51AlSTkMOHTlxFwvu5EgFlJxQitK0lfZcVkbdtHoovTCFCm8ovWXHloDS/aU4bBMTDfxtBFHf774shIqDywGNi+S4s/OWv+p+70GYT/KG9TJOJLu5xPZLfp6Qseh1/TBkfmnm3TLHlCUcPzl9bbgprqiyPsHkIYcHPNz3jdBP2SVycLh/eTC3xYyxTJ+8P9OeB7bOuFnc31LJL3MkwROQMQ4mabzpNNApELYQ6WzvDFplnuTBe5G5V/RZoecCb2xqZ8Ts6SJFmHZaASVoi9MdloWfXESjszMHMPClYPIiv94N3c87TizPs=
  on:
    all-branches: true
  environment:
    NODE_ENV: production
  skip_cleanup: true
